export const projects = [
  {
    title: "Medium",
    image: "/images/medium.png",
    tags: ["TypeScript", "NextJS", "ReactJS", "Sanity.io"],
    source: "https://github.com/DeveloperYamin/NextJs-Medium-Clone",
    visit: "http://next-js-medium-clone-zeta.vercel.app/",
    id: 0,
  },
  {
    title: "Disney+",
    image: "/images/disney-plus.png",
    tags: ["NextJS", "ReactJS", "Firebase", "TMDB API"],
    source: "https://github.com/DeveloperYamin/DisneyPlus-Clone",
    visit: "https://disney-plus-clone-ochre.vercel.app/",
    id: 1,
  },
  {
    title: "Linkedin",
    image: "/images/linkedIn.png",
    tags: ["Tailwind CSS", "MongoDB", "NextJS", "ReactJS"],
    source: "https://github.com/DeveloperYamin/NextJs-LinkedIn-Clone",
    visit: "http://next-js-linked-in-clone.vercel.app",
    id: 2,
  },
  {
    title: "Amazon",
    image: "/images/amazon.png",
    tags: ["Tailwind CSS", "Stripe", "NextJS", "ReduxJS"],
    source: "https://github.com/DeveloperYamin/Amazon-Clone",
    visit: "http://amazon-clone-pied-nu.vercel.app/",
    id: 3,
  },
  {
    title: "Instagram",
    image: "/images/instagram.png",
    tags: ["Tailwind CSS", "Firebase", "NextJS", "ReactJS"],
    source: "https://github.com/DeveloperYamin/Instagram-Clone",
    visit: "http://instagram-clone-lac-two.vercel.app/",
    id: 4,
  },
  {
    title: "Real Estate",
    image: "/images/real-estate.png",
    tags: ["Chakra UI", "Rapid API", "NextJS", "ReactJS"],
    source: "https://github.com/DeveloperYamin/Modern-Real-Estate",
    visit: "http://modern-real-estate.vercel.app/",
    id: 5,
  },
  {
    title: "Twitter",
    image: "/images/twitter.png",
    tags: ["Tailwind CSS", "Firebase", "NextJS", "ReactJS"],
    source: "https://github.com/DeveloperYamin/Twitter-Clone",
    visit: "http://twitter-clone-orpin-ten.vercel.app/",
    id: 6,
  },
  {
    title: "Google",
    image: "/images/google_search.png",
    tags: ["Tailwind CSS", "Google API", "NextJS", "ReactJS"],
    source: "https://github.com/DeveloperYamin/Google-Clone",
    visit: "http://google-clone-mocha-three.vercel.app/",
    id: 7,
  },
  {
    title: "Airbnb",
    image: "/images/airbnb.png",
    tags: ["Tailwind CSS", "Airbnb API", "NextJS", "ReactJS"],
    source: "https://github.com/DeveloperYamin/NextJs-Airbnb-Clone",
    visit: "https://next-js-airbnb-clone-sigma.vercel.app/",
    id: 8,
  },
];

export const TimeLineData = [
  { year: 2020, text: "Started my journey" },
  { year: 2022, text: "Worked as a Web developer" },
];
